version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      # Utiliser une image Docker avec Java 8 ou supérieur
      - image: cimg/openjdk:18.0.2

    steps:
      - checkout # Récupère le code source
      - run:
          name: Maven install dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Maven run tests
          command: mvn test
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml # Chemin vers votre rapport JaCoCo
          token: $CODECOV_TOKEN
workflows:
  version: 2.1
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only: master
