version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      # Utiliser une image Docker avec Java 8 ou supérieur
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout # Récupère le code source
      - run:
          name: Maven install dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Maven run tests
          command: mvn test
      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml # Chemin vers votre rapport JaCoCo
          token: $CODECOV_TOKEN
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only: master
