version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17  # Image CircleCI OpenJDK 17
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update
            apt-get install -y maven
      - run:
          name: Maven install dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Maven run tests
          command: mvn test
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only: master
