version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    steps:
      - checkout # Récupère le code source

      - run:
          name: Maven install dependencies
          command: mvn install -DskipTests=true

      - run:
          name: Maven run tests
          command: mvn test

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml # Chemin vers votre rapport de couverture (à adapter selon votre projet)

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only: master


